### ISSUE TITLE
Git conflict, 10000 changes unsaved

### ISSUE THREAD

**Issue by VIVALDI142857** [SENATOROVAI/datascience-Gleb#10]
### Attach a screenshot and write what did you do to fix the problem?

![image](https://github.com/user-attachments/assets/1e7a130d-a613-495f-a7db-dc2dd2114408)

### Error from the terminal / Code

(base) glebtrofimov@192 datascience-Gleb % git status
warning: could not open directory '.Trash/': Operation not permitted
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../../.CFUserTextEncoding
        ../../../.DS_Store
        ../../../.anaconda/
        ../../../.anydesk/
        ../../../.bash_profile
        ../../../.bitmonero/
        ../../../.cache/
        ../../../.conda/
        ../../../.condarc
        ../../../.config/
        ../../../.continuum/
        ../../../.cups/
        ../../../.gitconfig
        ../../../.gk/
        ../../../.idlerc/
        ../../../.ipynb_checkpoints/
        ../../../.ipython/
        ../../../.jupyter/
        ../../../.local/
        ../../../.matplotlib/
        ../../../.mysql_history
        ../../../.openjfx/
        ../../../.oracle_jre_usage/
        ../../../.profile
        ../../../.pylint.d/
        ../../../.shared-ringdb/
        ../../../.start_app_logs/
        ../../../.tcshrc
        ../../../.virtual_documents/
        ../../../.vscode/
        ../../../.xonshrc
        ../../../.zprofile
        ../../../.zsh_history
        ../../../.zsh_sessions/
        ../../../.zshrc
        ../../../Applications/
        ../../../Desktop/
        ../../
        ../../../Downloads/
        ../../../Library/
        ../../../Monero/
        ../../../Movies/
        ../../../Music/
        ../../../My Games/
        ../../../OneDrive
        ../../../Pictures/
        ../../../Public/
        ../../../PycharmProjects/
        ../../../Sites/
        ../../../Untitled-1.ipynb
        ../../../Untitled-2.py
        ../../../Untitled1.ipynb
        ../../../Untitled2.ipynb
        ../../../Untitled3.ipynb
        ../../../WarThunderLauncherLogs/
        ../../../cache/
        ../../../class Dog():.py
        ../../../test_db/

nothing added to commit but untracked files present (use "git add" to track)
(base) glebtrofimov@192 datascience-Gleb % 

### Expected behavior

All changes are supposed to be committed, I don't even have a clue what will happen if I try to commit my own changes: would that 10000 changes commit too?

### Actual behavior

First I installed 1.06.1 linter release, got in GitHub Desktop, that led to system collapse, I had to delete GitHub Desktop and VSCode and reinstall VSCode, now that unsaved changes appeared, what should I do?

**Comment by ruslansenatorov** [comment]
https://github.com/SENATOROVAI/datascience-Gleb/issues/11

**Comment by VIVALDI142857** [comment]
![image](https://github.com/user-attachments/assets/292fdad5-055e-4ff6-8f91-e46ae914b3a9)
Проблема была в том что гит был инициализирован через юзера
