### ISSUE TITLE
07.11deadline

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/datascience-Gleb#11]
https://github.com/SENATOROVAI/datascience-Gleb/blob/1ffdb3850e525c6dbe0a9220dbf981e363c75967/hw.txt#L51

**Comment by VIVALDI142857** [comment]
![Uploading Снимок экрана 2024-11-09 в 20.46.08.png…]()

**Comment by VIVALDI142857** [comment]
<img width="901" alt="Снимок экрана 2024-11-09 в 20 46 08" src="https://github.com/user-attachments/assets/4b4be96b-d939-45ca-abdf-b645eedea9a7">
<img width="905" alt="Снимок экрана 2024-11-09 в 20 46 18" src="https://github.com/user-attachments/assets/6125c826-2aa1-4a69-b5d3-81100374b1b1">
