### ISSUE TITLE
stash 

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/datascience-Gleb#12]
### STASH

1)https://t.me/c/1937296927/3602/25748?single

2)https://t.me/c/1937296927/3602/19531

- [x] Что такое стэш?  
  Общее объяснение концепции.

- [x] Как сохранить стэш?  
  Основные команды: 

- [x] Как восстановить стэш?  
  Основная команда:

- [x] Различие между стэшем и коммитом.  
  Когда лучше сохранить изменения в стэше, а когда коммитить.

- [x] Как просмотреть список сохраненных стэшей?  
  Использование команды:

- [x] Как удалить стэш?  
  Команды для удаления отдельных стэшей или всех сразу.

- [x] Практические примеры использования стэша.  
  Краткие сценарии, где стэш помогает.

**Comment by VIVALDI142857** [comment]
Stash - это конфликт изменений в файлах, возникающий при наличии нескольких версий таковых изменений.

Сохранить stash:

git stash push -m 'описание' или git stash: stash the uncommitted changes

Восстановить stash:

git stash apply

Различие между stashем и коммитом:
Stash это временное сохранение изменений, оно нужно, чтобы можно было хранить изменения без создания постоянных изменений.
commit сохраняет изменения навсегда, больше подходит для сохранения окончательных версий проекта. Также коммит является модулем самой ветки, тогда как stash им не является
Историю коммитов можно посмотреть с помощью функции git log

Посмотреть список сохраненных stashей - git stash list

 Как удалить стэш?  

git stash drop stash@{0} - удаляем ненужный стэш после применения

git stash pop - удаляет и применяет последний стэш (то же самое, что и git stash apply (применения Стеша) git stash drop(удаление примененного стеша)

Ситуации в которых не обойтись без Стеша:

Нам нужно совершить кардинальное изменение в проекте, в котором мы не уверены, так что нам, перед применением изменений стоит создать stash - это позволит нам откатиться на версию до изменений

При наличии нескольких контрибьюторов, во имя избежания конфликтов их изменений каждый может воспользоваться stashем после внесения правок другим, чтобы иметь возможность отменить/применить эти изменения
