### ISSUE TITLE
Pylint error on ubunti server

### ISSUE THREAD

**Issue by VIVALDI142857** [SENATOROVAI/datascience-Gleb#7]
### Hash commit / link

33cf5e15be6b08b0481eaa96b945fb1d5d413db5

### Attach a screenshot and write what did you do to fix the problem?

<img width="926" alt="Снимок экрана 2024-10-26 в 10 35 38" src="https://github.com/user-attachments/assets/260d2729-f1f2-4906-98e3-c8763a8d4ff8">

### Error from the terminal / Code

~pylint
************* Module chapter_11_classes_python_made_easy
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_2:1:0: R0903: Too few public methods (0/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_8:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_10:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_14:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_15:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_17:1:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_24:4:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Python/made-easy/chapter_11_classes_python_made_easy.ipynb:cell_24:39:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module chapter_12_errors_and_exceptions
Python/made-easy/chapter_12_errors_and_exceptions.ipynb:cell_9:1:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module chapter_8_data_structures_and_sequences_python_made_easy
Python/made-easy/chapter_8_data_structures_and_sequences_python_made_easy.ipynb:cell_3:1:20: R1721: Unnecessary use of a comprehension, use list('COUNTRY') instead. (unnecessary-comprehension)
Python/made-easy/chapter_8_data_structures_and_sequences_python_made_easy.ipynb:cell_9:1:21: R1721: Unnecessary use of a comprehension, use list(list(range(1, 26)) * 2) instead. (unnecessary-comprehension)

~black
--- log.ipynb	2024-10-26 13:26:50.013067+00:00:cell_6
+++ log.ipynb	2024-10-26 13:26:55.693282+00:00:cell_6
@@ -1,2 +1,2 @@
 # Сигнатура объекта
-str.lower?
+?str.lower
would reformat log.ipynb

Oh no! 💥 💔 💥
1 file would be reformatted, 16 files would be left unchanged.
Error: Process completed with exit code 1.

### Expected behavior

pylint no errors found (unnecessary list comprehensions are required by the exercise

### Actual behavior

No errors found by local linters - the opposite situation on Github

**Comment by ruslansenatorov** [comment]
https://github.com/SENATOROVAI/pre-commit/issues/4
