### ISSUE TITLE
14.11 deadline

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/datascience-Gleb#8]
https://github.com/SENATOROVAI/datascience-Gleb/blob/1ffdb3850e525c6dbe0a9220dbf981e363c75967/hw.txt#L86-L96

**Comment by VIVALDI142857** [comment]
<img width="1079" alt="Снимок экрана 2024-11-17 в 20 22 56" src="https://github.com/user-attachments/assets/34238aec-b233
<img width="1127" alt="Снимок экрана 2024
<img width="1407" alt="Снимок экрана 2024-11-12 в 22 10 28" src="https://github.com/user-attachments/assets/1ac10add-52c6-4c45-aa85-3eeef661d9c0">
-11-17 в 20 23 09" src="https://github.com/user-attachments/assets/dcd1d1a9-70f9-4420-bff1-3a6a24aa7316">
-4ce0-934c-59d002867a96">
https://github.com/VIVALDI142857/datascience-Gleb-fork/commit/48e0fe0642ad5b608b9982243a378cd5bf8d11dd

**Comment by VIVALDI142857** [comment]
I will fix all the mistakes in the commit, now Im not able to do it due to lack of time
